### ISSUE TITLE
Add Solana balance querying to `getBalances`

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/toolkit#180]
* Devnet and mainnet support
* Update the `hardhat balances` task as well
* Make sure the function handles a case when Solana key is not available (skip balance querying)
* Ensure `getBalances` still works in browser (Balances component in UniversalKit should show SOL balance)
* Ensure that address derived in the toolkit matches the one in the official Solana extension wallet for the same key/mnemonic.
* Add tests

**Comment by lukema95** [comment]
I would like to try it.

**Comment by fadeev** [comment]
If you think any changes to how `ZetaChainClient` is initialized need to be made, do comment! We can create a separate issue for that.

**Comment by lukema95** [comment]
> If you think any changes to how `ZetaChainClient` is initialized need to be made, do comment! We can create a separate issue for that.

Do we need to add a component to universalkit that connects to the Solana wallet?

**Comment by fadeev** [comment]
@lukema95 as part of a separate contribution, yes!

https://github.com/zeta-chain/universalkit/issues/22

**Comment by fadeev** [comment]
Seems like Solana can be added to RainbowKit:

https://docs.phantom.app/library-integrations/rainbowkit

**Comment by lukema95** [comment]
> Seems like Solana can be added to RainbowKit:
> 
> https://docs.phantom.app/library-integrations/rainbowkit

The Phantom wallet also supports EVM, so here RainbowKit only supports Phantom's EVM network, not Solana's. solana currently uses a lot of wallets and Backpack, and should have a tool to connect more Solana wallets.

**Comment by lukema95** [comment]
As the number of supported heterogeneous chains increases, perhaps we should build a tool to manage all wallets.

**Comment by fadeev** [comment]
Ok, for now `getBalances` should just probably just take a Solana address optionally like EVM and Bitcoin.
