### ISSUE TITLE
Update the toolkit to EVM_PRIVATE_KEY, SOLANA_PRIVATE_KEY, etc.

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/toolkit#187]
* Update `hardhat account`. When running account consider importing Solana private key from the default location of the Solana CLI.
* Update [`getHardhatConfig`](https://github.com/zeta-chain/toolkit/blob/e8bb0211e104a6bd5be864c9a9df3304452f6ba0/packages/client/src/getHardhatConfig.ts) to use `EVM_PRIVATE_KEY`
* Update templates to use `getHardhatConfig`
* Make sure that `npx hardhat verify` works out of the box with Blockscout (`getHardhatConfig` includes the required config, so it should work).

Update the [Intro doc](https://github.com/zeta-chain/docs/blob/8f747cacd32f0b738568314bb58970a7edaf3dad/src/pages/developers/tutorials/intro.mdx) both with how balances, account and contract verification works.

**Comment by fadeev** [comment]
> For Solana, do we still need to load files? Or do we just need to configure the SOLANA_PRIVATE_KEY environment variable? @fadeev

The `account` command should behave the same way as `balances`. Use `PRIVATE_KEY` if available (for backwards compatibility), use `SOLANA_PRIVATE_KEY` otherwise.

As for,

> When running account consider importing Solana private key from the default location of the Solana CLI.

I think it would be a good idea to prompt a user to import their Solana key from the default location into `SOLANA_PRIVATE_KEY`. Basically,

* if `SOLANA_PRIVATE_KEY` is not set AND `~/.config/solana/id.json` exists, prompt user, set `SOLANA_PRIVATE_KEY` in `.env` using the value from `~/.config/solana/id.json`.

**Comment by fadeev** [comment]
@lukema95 fwiw there are other items in this issue beyond `hardhat account`. They should be pretty straightforward.

**Comment by lukema95** [comment]
> @lukema95 fwiw there are other items in this issue beyond `hardhat account`. They should be pretty straightforward.

@fadeev 

For:
>Update [getHardhatConfig](https://github.com/zeta-chain/toolkit/blob/e8bb0211e104a6bd5be864c9a9df3304452f6ba0/packages/client/src/getHardhatConfig.ts) to use EVM_PRIVATE_KEY
Update templates to use getHardhatConfig
Make sure that npx hardhat verify works out of the box with Blockscout (getHardhatConfig includes the required config, so it should work).

Since it's currently backward compatible, it doesn't look like we need to change it, right?

For:
>Update the [Intro doc](https://github.com/zeta-chain/docs/blob/8f747cacd32f0b738568314bb58970a7edaf3dad/src/pages/developers/tutorials/intro.mdx) both with how balances, account and contract verification works.

We can update it.

**Comment by fadeev** [comment]
@lukema95 right, just the docs then. Thanks!
