### ISSUE TITLE
Module not found: Can't resolve '@zetachain/protocol-contracts-solana/idl/gateway.json'

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/toolkit#208]
I used `@zetachain/toolkit": "^13.0.0-rc9"` in `universalkit` and then used the `universalkit` package in `tempalte` and got an error when starting:
```
 ⨯ ./node_modules/@zetachain/universalkit/dist/index-DrTHSGl9.mjs:5:1
Module not found: Can't resolve '@zetachain/protocol-contracts-solana/idl/gateway.json'
```

**Comment by fadeev** [comment]
Are you using `yarn link`? Because when installed, `protocol-contracts-solana` should have the IDL file.

<img width="1840" alt="Screenshot 2024-12-27 at 13 23 42" src="https://github.com/user-attachments/assets/3d780fac-2587-4cd9-a23e-b02338e1a7a9" />

**Comment by lukema95** [comment]
> Are you using `yarn link`? Because when installed, `protocol-contracts-solana` should have the IDL file.
> 
> <img alt="Screenshot 2024-12-27 at 13 23 42" width="1840" src="https://private-user-images.githubusercontent.com/332151/398915664-3d780fac-2587-4cd9-a23e-b02338e1a7a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMDQ3NzEsIm5iZiI6MTczNTMwNDQ3MSwicGF0aCI6Ii8zMzIxNTEvMzk4OTE1NjY0LTNkNzgwZmFjLTI1ODctNGNkOS1hMjNlLWIwMjMzOGUxYTdhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxMzAxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWVjZjZhNWJiOGEyMjhmOTcxY2M2MjI4NjJiMDk1MmZiNzg5OWQ3MWViNmEyMmI5OTAyOTgzYzhjMDJmNDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5OjAdAh5PYeoKuYf3bAyhWGYeO1ayfhmYMg-ryWmf70">

Yes, I am using `yarn link`. Looking at `universalkit` node_modules, `toolkit` compiled packages do not seem to contain `@zetachain/ protocol-contract-solana` packages
<img width="330" alt="image" src="https://github.com/user-attachments/assets/ab655172-d068-486f-a34e-d4742fe6dc24" />
I'm done developing the code [here](https://github.com/zeta-chain/universalkit/pull/31), but it seems a little difficult to test its functionality

**Comment by fadeev** [comment]
@lukema95 I think it's because when you yarn link, it doesn't install all required packages. As a workaround, I suggest you temporarily `yarn add` protocol-contracts-solana into UniversalKit for testing purposes.

Alternatively, unlink, install latest toolkit rc9 into the UniversalKit and it should pull solana protocol contracts.
