### ISSUE TITLE
[BUG] Inclusion of `@zetachain/toolkit/tasks` in the hardhat config beakes `hardhat console`

### ISSUE THREAD

**Issue by ustas-eth** [zeta-chain/toolkit#31]
Bug (`hardhat console`):
![VSCodium_DdNYRFd3Ai](https://github.com/NomicFoundation/hardhat/assets/82833595/f06d3d8f-205f-4fb6-981f-18c887c61bf8)
Expected behavior (just `node`):
![VSCodium_31EgqDfwba](https://github.com/NomicFoundation/hardhat/assets/82833595/650820e8-4c4e-4855-93bf-3c96ab118498)

When I'm trying to type anything in the prompt field it corrupts the text.
I tried several different consoles:
- standard PowerShell
- integrated PS in VSCode
- Windows terminal preview
- CMD

I also tried to reinstall the node_modules.

Windows 10 19044.3086, hardhat 2.17.1, toolbox 1.0.8-athens3

**Comment by fadeev** [comment]
Can reproduce, looking into it.

**Comment by fadeev** [comment]
I've localized the problem to the `faucet` task.

**Comment by fadeev** [comment]
To reproduce a problem with `readline` do the following.

```
mkdir foo
cd foo
npx hardhat
```

`tasks/test.ts`:

```
import { task } from "hardhat/config";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { createInterface } from "node:readline";

const readline = createInterface({
  input: process.stdin,
  output: process.stdout,
});

const main = async (args: any, hre: HardhatRuntimeEnvironment) => {
  readline.question("question", (userRes: any) => {
    console.log(userRes);
  });
};

task("test", "", main);
```

`hardhat.config.ts`:

```
import "./tasks/test";
```

The console is no longer working properly:

```
npx hardhat console
```

Fix the task by instantiating `readline` as a local variable:

```
import { task } from "hardhat/config";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { createInterface } from "node:readline";

const readline = createInterface({
  input: process.stdin,
  output: process.stdout,
});

const main = async (args: any, hre: HardhatRuntimeEnvironment) => {
  readline.question("question", (userRes: any) => {
    console.log(userRes);
  });
};

task("test", "", main);
```

The console is working fine:

```
npx hardhat console
```
